version: '3.9'

volumes:
  postgres_data:
  phoenix_data:

networks:
  task_mcp_network:

services:
  postgres:
    image: postgres:alpine3.23
    container_name: task_mcp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - task_mcp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  phoenix:
    image: arizephoenix/phoenix:12.27.0
    container_name: task_mcp_phoenix
    restart: unless-stopped
    networks:
      - task_mcp_network
    ports:
      - "6006:6006"
      - "4317:4317"
    volumes:
      - phoenix_data:/data

  app:
    build: .
    container_name: task_mcp_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      phoenix:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - task_mcp_network
